name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: SKIP_ENV_VALIDATION=true npm run build
        env:
          SKIP_ENV_VALIDATION: true
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'dummy_url_for_ci' }}
          AUTH_URL: ${{ secrets.AUTH_URL || 'http://localhost:3000' }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY || 'dummy_key_for_ci' }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM || 'test@example.com' }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID || 'dummy_id_for_ci' }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET || 'dummy_secret_for_ci' }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET || 'dummy_secret_for_ci' }}